### ISSUE TITLE
Rendering error

### ISSUE THREAD

**Issue by NaikSoftware** [PegasisForever/keep_keyboard_popup_menu#6]
Snippet that cause arror

```
WithKeepKeyboardPopupMenu(
                childBuilder: (context, openPopup) => InkWell(
                    borderRadius: borderRadius,
                    onTap: () {
                      if (_canShowMenu) {
                        openPopup();
                      }
                    },
                    onLongPress: () {
                      if (_canShowMenu) {
                        HapticFeedback.vibrate();
                        openPopup();
                      }
                    },
                    child: child),
                menuBuilder: (context, closePopup) =>      Material(
          elevation: 8,
          borderRadius: BorderRadius.circular(8),
          color: BrandColors.brandWhite,
          child: Padding(
            padding: const EdgeInsets.symmetric(vertical: 8),
            child: ConstrainedBox(
                constraints: BoxConstraints(maxWidth: 200),
                child: Column(children: items)),
          )),
              ))),
```

Example also not working. 
Flutter (Channel beta, 2.4.0-4.2.pre, on Ubuntu 20.04.2 LTS 5.4.0-77-generic, locale en_US.UTF-8)

```
======== Exception caught by rendering library =====================================================
The following assertion was thrown during paint():
Attempted to create a handle to an already disposed layer: ClipRectLayer#4532a(handles: 0, clipRect: Rect.fromLTRB(0.0, 0.0, 224.0, 160.0), clipBehavior: Clip.hardEdge).
'package:flutter/src/rendering/layer.dart':
Failed assertion: line 620 pos 7: 'layer?.debugDisposed != true'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  AnnotatedRegion<SystemUiOverlayStyle> AnnotatedRegion:file:///home/naik/IdeaProjects/flutter-app/lib/main.dart:161:21
When the exception was thrown, this was the stack: 
#2      LayerHandle.layer= (package:flutter/src/rendering/layer.dart:620:7)
#3      ContainerLayer.append (package:flutter/src/rendering/layer.dart:1156:25)
#4      PaintingContext.appendLayer (package:flutter/src/rendering/object.dart:237:21)
#5      PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:395:5)
#6      PaintingContext.pushClipRect (package:flutter/src/rendering/object.dart:454:7)
#7      _RenderPercentageSize.paint (package:keep_keyboard_popup_menu/src/percentage_size.dart:71:30)
#8      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2409:7)
#9      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#10     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#11     _RenderInkFeatures.paint (package:flutter/src/material/material.dart:553:11)
#12     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2409:7)
#13     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#14     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#15     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:398:12)
#16     RenderPhysicalModel.paint (package:flutter/src/rendering/proxy_box.dart:1941:15)
#17     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2409:7)
#18     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#19     RenderOpacity.paint (package:flutter/src/rendering/proxy_box.dart:903:17)
#20     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2409:7)
#21     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#22     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#23     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:398:12)
#24     PaintingContext.pushOpacity (package:flutter/src/rendering/object.dart:619:5)
#25     RenderOpacity.paint (package:flutter/src/rendering/proxy_box.dart:907:23)
#26     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2409:7)
#27     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#28     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:79:15)
#29     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2409:7)
#30     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#31     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2794:15)
#32     RenderStack.paintStack (package:flutter/src/rendering/stack.dart:629:5)
#33     RenderStack.paint (package:flutter/src/rendering/stack.dart:645:7)
#34     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2409:7)
#35     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#36     _RenderTheatre.paintStack (package:flutter/src/widgets/overlay.dart:782:15)
#37     _RenderTheatre.paint (package:flutter/src/widgets/overlay.dart:800:7)
#38     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2409:7)
#39     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#40     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#41     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2409:7)
#42     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#43     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#44     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2409:7)
#45     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#46     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#47     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2409:7)
#48     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#49     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#50     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:398:12)
#51     RenderAnnotatedRegion.paint (package:flutter/src/rendering/proxy_box.dart:5417:13)
#52     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2409:7)
#53     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#54     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#55     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2409:7)
#56     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#57     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#58     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2409:7)
#59     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#60     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#61     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2409:7)
#62     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#63     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#64     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2409:7)
#65     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#66     RenderView.paint (package:flutter/src/rendering/view.dart:209:15)
#67     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2409:7)
#68     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:141:11)
#69     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:100:5)
#70     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:979:29)
#71     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:466:19)
#72     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:878:13)
#73     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:330:5)
#74     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1143:15)
#75     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1080:9)
#76     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
#80     _invoke (dart:ui/hooks.dart:164:10)
#81     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:262:5)
#82     _drawFrame (dart:ui/hooks.dart:127:31)
(elided 5 frames from class _AssertionError and dart:async)
The following RenderObject was being processed when the exception was fired: _RenderPercentageSize#a18cd relayoutBoundary=up6
...  needs compositing
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(0.0<=w<=376.7, 0.0<=h<=766.2)
...  size: Size(224.0, 160.0)
...  alignment: Alignment.center
RenderObject: _RenderPercentageSize#a18cd relayoutBoundary=up6
  needs compositing
  parentData: <none> (can use size)
  constraints: BoxConstraints(0.0<=w<=376.7, 0.0<=h<=766.2)
  size: Size(224.0, 160.0)
  alignment: Alignment.center
...  child: RenderConstrainedBox#55f97 relayoutBoundary=up7
...    needs compositing
...    parentData: offset=Offset(0.0, 0.0) (can use size)
...    constraints: BoxConstraints(0.0<=w<=376.7, 0.0<=h<=766.2)
...    size: Size(224.0, 160.0)
...    additionalConstraints: BoxConstraints(112.0<=w<=280.0, 0.0<=h<=Infinity)
...    child: RenderRepaintBoundary#4b056 relayoutBoundary=up8
...      needs compositing
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(112.0<=w<=280.0, 0.0<=h<=766.2)
...      layer: OffsetLayer#619a9 DETACHED
...        engine layer: OffsetEngineLayer#33dfa
...        handles: 1
...        offset: Offset(-44.4, -31.7)
...      size: Size(224.0, 160.0)
...      metrics: 0.0% useful (1 bad vs 0 good)
...      diagnosis: insufficient data to draw conclusion (less than five repaints)
...      child: RenderCustomPaint#4b004 relayoutBoundary=up9
...        needs compositing
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(112.0<=w<=280.0, 0.0<=h<=766.2)
...        size: Size(224.0, 160.0)
...        child: RenderRepaintBoundary#dc3a3 relayoutBoundary=up10
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(112.0<=w<=280.0, 0.0<=h<=766.2)
...          layer: OffsetLayer#bf188 DETACHED
...            engine layer: OffsetEngineLayer#8ef09
...            handles: 2
...            offset: Offset(0.0, 0.0)
...          size: Size(224.0, 160.0)
...          metrics: 0.0% useful (1 bad vs 0 good)
...          diagnosis: insufficient data to draw conclusion (less than five repaints)
```

**Comment by PegasisForever** [comment]
Thank you for opening an issue, I can reproduce it on flutter beta.

The package works correctly on latest stable, you can use that while I'm finding a fix.

**Comment by jangruenwaldt** [comment]
Now that 2.5 is out, also occurs on stable sadly...

Any update ETA? Kinda need it... I would also submit PR if I knew how to fix

**Comment by jangruenwaldt** [comment]
I randomly found a fix, but I'm not very familiar with flutter sub-widget level code, but if you just need a working version see my fork:

https://github.com/OurFlat/keep_keyboard_popup_menu

**Comment by NaikSoftware** [comment]
@jangruenwaldt also working for me, thanks 😃

**Comment by tremp-m** [comment]
@jangruenwaldt for me too, thx

**Comment by MarkAMoussa** [comment]
@jangruenwaldt Thanks a lot this is really helpful
